version: 2
jobs:
  build:
    environment:
      NODE_IMAGE_VERSION: '12'
    docker:
      - image: circleci/node:"${NODE_IMAGE_VERSION}"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint
          command: yarn lint
      # - run:
      #     name: Test
      #     command: yarn test
  deploy:
    environment:
      NODE_IMAGE_VERSION: '12'
      GIT_EMAIL: aayhrot@gmail.com
      GIT_USER: rot1024
    docker:
      - image: circleci/node:"${NODE_IMAGE_VERSION}"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Set up git config
          command: |
            git config --global user.email $GIT_EMAIL
            git config --global user.name $GIT_USER
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          command: yarn deploy
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
