version: 2
jobs:
  build:
    environment:
      NODE_IMAGE_VERSION: '12'
      DEPLOY_BRANCH: master
    docker:
      - image: circleci/node:"${NODE_IMAGE_VERSION}"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint
          command: yarn lint
      # - run:
      #     name: Test
      #     command: yarn test
      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              yarn build
              yarn deploy
            fi
